version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.2
    - 4.3.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  registries:
  - npm-registry-registry-npmjs-org
