language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: DL090o0JEOFYiC756Fth7pIYaBgT8Zdjr5sNr75FAdKi7VDp4nPxJWQ6asA0YLUSesEzj1O7cxsUIvetTAkn1KNQS/KhNfcfRTPaMdFe13VEly9NajPKJV7r9VEBBZhHy/uBd+H0XFVv8zxSsW6CiHJy5E9OapQcZ8N04VEJdc8fn+TFIZcpdOmedamIlY9Zt0dtY27ccK8rIhaFJXDc00EaSlYRXLyfH8K2SmybqfXha884/67fRCAxfeowqh+F8wZyI3QinrrU6KXhAHSstt0efwWAcJHSAs4sEQmRHDHcDokPaXSVi4FiCJV4hpuSMorPoV86WGxzFvkEu9xBfJ3I1iwZrJwxdmrNweUwrKkiyVsl1NksXakadD4wkIjb8XRq/R1lSdkGupFmSeg0B+WsRvzfAnGOOC3wM/QtjVVObKOFRV2YsgDra5sEVQQ8Sr0sEmHtQTkcMoqCGJtvpscdRjiFLapbcWXVSk1rdW70ZTqy65RJE5knSEiKv4DPVEUgmcXG0RD8LOUDUNVtyDkCfwJCV+5wFA+X6Ov6fM4flv81HRz1hS+5ievJSAHLypvepGPzVhQlsn9CwteqdXh9MF74BjKe4JG8KCYyv55XJkjsOQw6IWGC6hI9s861/NKlR5prcwYUbSmsAtcca2GdVCvv37ENFN7WInzU/ts=
  - secure: N3lE8FXgQiLDZwtkbHiSLJiWBJ3dh2gywov876nyW0iCkCDyIeeOLYxyAMeaduvcyE+EnU9UrWQdGDAygGB0UYCflrCLbe0YD3IFSI+qiJ4lmU44i2mKalSItb6dbJPPwPe1G+1b7cH0Q+EIuVks/j2BdcCzZ/+4pOODPaue2A0VQY2E8IgZToDyHIdsj73xQUlZ1/lzVfRoQwn0VSgvb/8zZ8/vOxv/aZs9oiG5QH5sm14/TTZ09h+fanVJGeQ/grOusEaD0DyoNY2RrpPzUCgy5uBuX9JHljYEKjX/PqxlJAtim5U26nWOKfiULwSh5RWui4gTpPGfa5RBitWqhSpwr/WaVhiNOZoOaX3PJDmi7IuZOd1ul4ByWmDiy7ySZQp4lKmy2vgkU9n2qQrBP8dYFJFACo2/Rl24VRj1EZDo19FFINzUktSsnL1DU++4w9ZiOHtAVqEMrEeHd/rXEqyglvqjQHX9oVwnA5XjN7wGO+XoC85gwch2oEe07E0nlPbB5m1rolrULvgaHce71Bg53JrsoOUB7VKabV5CAvRvdK4QO3kuZaB894qIq2c6tghyTZgkjzT4J3mT7xN9B3d//204HEbHdtooaZJBTXGmkqHbD/lSZuL3NrZgj6aIITO+cwLjfZQZ7yy3xSUHuXuPwMbEViQcGcBEzdFrIsc=
