language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
install:
- npm install
- gem install travis
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
  - secure: DL090o0JEOFYiC756Fth7pIYaBgT8Zdjr5sNr75FAdKi7VDp4nPxJWQ6asA0YLUSesEzj1O7cxsUIvetTAkn1KNQS/KhNfcfRTPaMdFe13VEly9NajPKJV7r9VEBBZhHy/uBd+H0XFVv8zxSsW6CiHJy5E9OapQcZ8N04VEJdc8fn+TFIZcpdOmedamIlY9Zt0dtY27ccK8rIhaFJXDc00EaSlYRXLyfH8K2SmybqfXha884/67fRCAxfeowqh+F8wZyI3QinrrU6KXhAHSstt0efwWAcJHSAs4sEQmRHDHcDokPaXSVi4FiCJV4hpuSMorPoV86WGxzFvkEu9xBfJ3I1iwZrJwxdmrNweUwrKkiyVsl1NksXakadD4wkIjb8XRq/R1lSdkGupFmSeg0B+WsRvzfAnGOOC3wM/QtjVVObKOFRV2YsgDra5sEVQQ8Sr0sEmHtQTkcMoqCGJtvpscdRjiFLapbcWXVSk1rdW70ZTqy65RJE5knSEiKv4DPVEUgmcXG0RD8LOUDUNVtyDkCfwJCV+5wFA+X6Ov6fM4flv81HRz1hS+5ievJSAHLypvepGPzVhQlsn9CwteqdXh9MF74BjKe4JG8KCYyv55XJkjsOQw6IWGC6hI9s861/NKlR5prcwYUbSmsAtcca2GdVCvv37ENFN7WInzU/ts=
